### ISSUE TITLE
Events for payment are not being fired

### ISSUE THREAD

**Issue by andrzejschmidt** [AppWerft/Ti.Paypal#3]
Hey, 

I have got a problem, paypal account is being charged fine, but seems like 'paymentDidCancel', 'paymentDidComplete' are not fired, instead of I'm getting:

> [ERROR] :  E/paypal.sdk: request failed with server response:Canceled

Any ides why, am I simply missing something? This is the code I'm using to test it (default index.js from Alloy project):

``` javascript
var PayPal = require("de.appwerft.paypal");

PayPal.initialize({
    clientIdSandbox : "<SANDBOX_ID>",
    clientIdProduction : "<PRODUCTION_ID>",
    environment : PayPal.ENVIRONMENT_SANDBOX // or: ENVIRONMENT_PRODUCTION
});

var configuration = PayPal.createConfiguration({
    merchantName : "John Doe",
    merchantPrivacyPolicyURL : "http://google.com",
    merchantUserAgreementURL : "http://google.com",
    locale : "en" // Any ISO 639-1
});

var payment = PayPal.createPayment({
    // Required
    configuration : configuration,
    currencyCode : "GBP",
    amount : 5, // Has to match the amount of your items if you set them
    shortDescription : "Purchase - Test",
    intent : PayPal.PAYMENT_INTENT_SALE, // or: PAYMENT_INTENT_AUTHORIZE, PAYMENT_INTENT_ORDER

});

payment.addEventListener("paymentDidCancel", function(e) {
    Ti.API.warn("paymentDidCancel");
});

payment.addEventListener("paymentDidComplete", function(e) {
    Ti.API.warn("paymentDidComplete");
    alert(JSON.stringify(e));
});

var window = $.index;
window.add(createButton("Simple Payment", doSimplePayment));

window.open();

function createButton(title, cb) {
    var btn = Ti.UI.createButton({
        title : title,
        width : 300,
        color : "#fff",
        height : 40,
        backgroundColor : "#333",
        top : 40
    });
    btn.addEventListener("click", cb);
    return btn;
}

function doSimplePayment() {
    payment.show();
}
```

**Comment by AppWerft** [comment]
Please try first this:
```javascript
var payment = PayPal.createPayment({
    // Required
    configuration : PayPal.createConfiguration({
    merchantName : "John Doe",
    merchantPrivacyPolicyURL : "http://google.com",
    merchantUserAgreementURL : "http://google.com",
    locale : "en" // Any ISO 639-1
	}),
    currencyCode : "GBP",
    amount : 5, // Has to match the amount of your items if you set them
    shortDescription : "Purchase - Test",
    intent : PayPal.PAYMENT_INTENT_SALE, // or: PAYMENT_INTENT_AUTHORIZE, PAYMENT_INTENT_ORDER

});
````

**Comment by andrzejschmidt** [comment]
Thanks, this solved the error, it is not appearing now, but event listeners are still not fired.

**Comment by AppWerft** [comment]
OK, Currently I have no time for it. next week?

**Comment by andrzejschmidt** [comment]
Great, thanks!

**Comment by eolverabea** [comment]
Hi!
 I have the same problem andrzejschmidt , and I have a question about the items , I try to add one or more and send me the below error:
[ERROR] : KrollProxy: (KrollRuntimeThread) [2,392] Error creating proxy
[ERROR] : KrollProxy: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.util.ArrayList
[ERROR] : KrollProxy: at de.appwerft.paypal.PaymentProxy.handleCreationDict(PaymentProxy.java:225)
[ERROR] : KrollProxy: at org.appcelerator.kroll.KrollProxy.handleCreationArgs(KrollProxy.java:227)
[ERROR] : KrollProxy: at org.appcelerator.kroll.KrollProxy.setupProxy(KrollProxy.java:135)
[ERROR] : KrollProxy: at org.appcelerator.kroll.KrollProxy.createProxy(KrollProxy.java:143)
[ERROR] : KrollProxy: at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[ERROR] : KrollProxy: at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:177)
[ERROR] : KrollProxy: at org.appcelerator.kroll.KrollRuntime.handleMessage(KrollRuntime.java:319)
[ERROR] : KrollProxy: at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:203)
[ERROR] : KrollProxy: at android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR] : KrollProxy: at android.os.Looper.loop(Looper.java:137)

**Comment by AppWerft** [comment]
Please use the updated API (without createConfiguration and createItem)

**Comment by eolverabea** [comment]
Use the updated code ( copy and paste) on but still sends me the same error , I am using the version 1.0.0 de.appwerft.paypal

**Comment by AppWerft** [comment]
I'm working on it

**Comment by AppWerft** [comment]
There is a new version. On console is a note from Paypal library. please test if it appears. Maybe a little issue with fireEvent to jS layer.

Good luck!

**Comment by eolverabea** [comment]
no longer returns me the error of the items , only the server,  thank you very much

**Comment by AppWerft** [comment]
I understood this. The PP-Server write to console, but the js event is missing?

**Comment by eolverabea** [comment]
When the transaction does not release the event response sends this response:
E/paypal.sdk: request failed with server response:Canceled
This happened a few days ago , I did some tests days ago and if he could launch events ,

[WARN] :   W/paypal.sdk: fm SN:8 PayPal Debug-ID: 5188b7814d39e [sandbox, 2.14.2;release]
[WARN] :   W/paypal.sdk: fr SN:3 PayPal Debug-ID: 163a6150b9ffe [sandbox, 2.14.2;release]
[WARN] :   W/paypal.sdk: fd SN:11 PayPal Debug-ID: 38bdeee03b18c [sandbox, 2.14.2;release]
[ERROR] :  E/paypal.sdk: request failed with server response:Canceled

**Comment by andrzejschmidt** [comment]
Yeah, I can confirm, tried it with multiple items and works now. Like eolverabea I'm getting warnings from paypal sdk, but events are still missing.

**Comment by eolverabea** [comment]
Does not return any event , if the transaction was canceled or was performed successfully , I would not know what has happened with the transaction

**Comment by AppWerft** [comment]
Did you see events on console (they will generated in callback part of code)

**Comment by AppWerft** [comment]
Now is a new version out.

**Comment by andrzejschmidt** [comment]
Hey, I have used the new 1.0.4 version, but can't see anything. Here's [a link](https://gist.github.com/andrzejschmidt/1a5a52e88e0da1f4374a046811ba0937) to my full log, from installing to paying and finally closing the app.

**Comment by AppWerft** [comment]
Hello,
I sent a ticket to paypal:

_Hi PP,

in my android app I have realized a payment gateway. By using of sandbox userID and successful login with test user and succesfull payment I see this on console an the 'onActivityResult' event never happens.

[WARN] :   W/paypal.sdk: fm SN:10 PayPal Debug-ID: ba70f9d9579b [sandbox, 2.14.2;release]
[WARN] :   W/paypal.sdk: fg SN:12 PayPal Debug-ID: 1a508e303ae4c [sandbox, 2.14.2;release]
[WARN] :   W/paypal.sdk: fd SN:13 PayPal Debug-ID: 253a4ff871291 [sandbox, 2.14.2;release]
[ERROR] :  E/paypal.sdk: request failed with server response:Canceled

Can you help?

Best regards

Rainer_ 

There is a new version with verbose debug output.

```javascript
PayPalModule.setDebug(1);
```

**Comment by AppWerft** [comment]
I found https://github.com/paypal/PayPal-Android-SDK/issues/258
Maybe this is the issue. I will modify the version of okhttp

**Comment by AppWerft** [comment]
The same issue with okhttp3.0.1 Currently I don't see a solution. Lets wait to PP answer.

**Comment by eolverabea** [comment]
I also have a ticket with paypal.

**Comment by eolverabea** [comment]
This is what I answered Paypal:

If I look into one of the debug ID:
[WARN] : W/paypal.sdk: fg SN:12 PayPal Debug-ID: 1a508e303ae4c [sandbox,
2.14.2;release]
I can see that the transaction is completed with the transaction ID: 6NS48896RP671784A 
In this case, I believe this could be due to the SDK issue, https://github.com/paypal/PayPal-Android-SDK/issues/243
You may reach out github support for further assistance on this issue.
Sincerely,
Anis
Merchant Technical Support
PayPal

**Comment by eolverabea** [comment]
Not yet able to have something ?

**Comment by AppWerft** [comment]
Today have found the issue and see a solution. I hope to solve today and the we have a new version.

**Comment by eolverabea** [comment]
There's something wrong in the code of java in the way it captures events.
